# Generated by Django 3.2 on 2023-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
