# Generated by Django 3.2 on 2023-09-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total_questions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
